#!/usr/bin/env bash
# what record domain type

what_record()
{
    ouput=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $ouput" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    what_record "$1" "www"
    what_record "$1" "lb-01"
    what_record "$1" "web-01"
    what_record "$1" "web-02"
elif [ "$#" == 2 ]
then
    what_record "$1" "$2"
fi
