#!/usr/bin/env bash
# comment to explain
apt-get -y update
apt-get -y  install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default
service nginx start
