#!/usr/bin/env bash
# comment
apt-get -y update
apt-get -y  install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/server {/a\    location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
}' /etc/nginx/sites-available/default
sudo service nginx restart
