#!/usr/bin/env bash
# comment
apt-get -y update
apt-get -y  install nginx
sudo sed -i '/server {/a\    location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
}' /etc/nginx/sites-available/default
nginx -s reload
