#!/usr/bin/env bash
#  a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash
listofpids=$(pgrep bash)
for id in $listofpids
do
    echo "$id bash"
done
