#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely
handler() {
    echo "I am invincible!!!"
}
trap 'handler' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
