#!/usr/bin/env bash
# The content of the current directory
mapfile -t currentdirlist < <(ls)

for file in "${currentdirlist[@]}"
do
    if [ "${file:0:1}" == "-" ]
    then
        onlypart="${file:1}"
    fi

    echo "$onlypart"
done
