#!/usr/bin/env bash
# The content of the current directory
mapfile -t currentdirlist < <(ls)

for file in "${currentdirlist[@]}"
do
    if [ -f $file ]
    then
        onlypart=$file
        if [ "${file:1:1}" == "-" ] || [ "${file:2:1}" == "-" ]
        then    
            onlypart="${file:2}"
        fi
        if [ "${onlypart:0:1}" == "-" ]
        then
            onlypart="${onlypart:1}"
        fi
        echo "$onlypart"
    fi
done
