#!/usr/bin/env bash

# The content of the current directory
mapfile -t currentdirlist < <(ls)

for file in "${currentdirlist[@]}"
do
    onlypart="${file:2}"

    if [ "${onlypart:0:1}" == "-" ]
    then
        onlypart="${onlypart:1}"
    fi

    echo "$onlypart"
done
