#!/usr/bin/env bash

lIST=('10-fizzbuzz' '9-to_file_or_not_to_file' '8-for_ls' '7-clock' '6-superstitious_numbers' '5-4_bad_luck_8_is_your_chance' '4-if_9_say_hi' '3-until_best_school' '2-while_best_school' '1-for_best_school' '0-RSA_public_key.pub')
for i in "${lIST[@]}"
do
    touch "$i"
    echo "#!/usr/bin/env bash" >> "$i"
done
