#!/usr/bin/env bash
# Run nginx as the nginx user
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/conf.d/default.conf
sed -i 's/listen [::]:80;/listen [::]:8080;/' /etc/nginx/conf.d/default.conf
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
